### 회원가입
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "nickname": "testuser",
  "password": "password123"
}


### 로그인
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}


### 상품 등록
POST http://localhost:5000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2Mjg3NSwiZXhwIjoxNzQyODY2NDc1fQ.85HJn42tXt-Ge8ndJJnQCdG8yWNCYJzbEUgneJGSouY

{
  "name": "Test Product",
  "description": "This is a test product.",
  "price": 10000,
  "tags": ["test", "product"]
}

###

### 상품 수정
PATCH http://localhost:5000/products/{productId}
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Updated Product",
  "description": "Updated description.",
  "price": 12000,
  "tags": ["updated", "product"]
}

###

### 상품 삭제
DELETE http://localhost:5000/products/{productId}
Authorization: Bearer 

###

### 게시글 등록
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2MjY5NywiZXhwIjoxNzQyODY2Mjk3fQ.jTaxM1KQkIzOQQAv87hTrMlWAuHAdrsqjX_eFAg9xF4

{
  "title": "Test Post",
  "content": "This is a test post."
}

###

### 게시글 수정
PATCH http://localhost:5000/posts/{postId}
Content-Type: application/json
Authorization: Bearer 

{
  "title": "Updated Post",
  "content": "Updated content."
}

###

### 게시글 삭제
DELETE http://localhost:5000/posts/{postId}
Authorization: Bearer 

###

### 댓글 등록 (상품)
POST http://localhost:5000/comments/product/{productId}
Content-Type: application/json
Authorization: Bearer 

{
  "content": "This is a test comment on the product."
}

###

### 댓글 수정 (상품)
PATCH http://localhost:5000/comments/{commentId}
Content-Type: application/json
Authorization: Bearer 

{
  "content": "Updated comment content."
}

###

### 유저 정보 조회
GET http://localhost:5000/users/m
Authorization: Bearer 

###

### 유저 정보 수정
PATCH http://localhost:5000/users/m
Content-Type: application/json
Authorization: Bearer 

{
  "nickname": "updatedUser",
  "image": "new-image-url"
}

###

### 비밀번호 변경
PATCH http://localhost:5000/users/m/password
Content-Type: application/json
Authorization: Bearer 

{
  "oldPassword": "password123",
  "newPassword": "newPassword123"
}
